# Base nix-on-droid configuration
# Shared nix settings and environment configuration
{
  config,
  lib,
  pkgs,
  outputs,
  hostname,
  username,
  ...
}: let
  packages = import ../../packages.nix {inherit pkgs;};

  # Path to termux.env containing Android environment variables
  # This file is generated by the Termux app with ANDROID_*, TERMUX_*, PREFIX, etc.
  termuxEnvPath = "/data/data/com.termux.nix/files/usr/etc/termux/termux.env";
in {
  # Environment packages for nix-on-droid (system-level)
  # Uses shared package lists from common/packages.nix
  # Note: time.timeZone (in locale.nix) creates /etc/zoneinfo symlink to tzdata
  environment.packages =
    packages.coreUtils
    ++ packages.compression
    ++ packages.networkTools
    ++ packages.systemTools
    ++ packages.editors
    ++ packages.modernCli
    ++ packages.devTools;

  # Backup etc files instead of failing to activate generation if a file already exists in /etc
  environment.etcBackupExtension = ".bak";

  # Read the changelog before changing this value
  system.stateVersion = "24.05";

  # Set up nix for flakes
  nix.extraOptions = ''
    experimental-features = nix-command flakes
  '';

  # User configuration (uses username from flake)
  user = {
    userName = username;
    group = username;
    shell = "${pkgs.zsh}/bin/zsh";
  };

  # Set hostname in /etc/hosts
  networking.hosts = {
    "127.0.0.1" = [hostname];
  };

  # Patch login-inner to source Android environment variables at the EARLIEST point
  # This injects termux.env sourcing right after "set -eo pipefail" but before
  # anything else (including motd and session-init).
  #
  # We patch both /usr/lib/login-inner (current) and /usr/lib/.login-inner.new (staged)
  # because nix-on-droid updates login-inner in stages.
  #
  # IMPORTANT: We filter out PATH, HOME, USER, TMPDIR, LANG, TERM as they would
  # conflict with nix-on-droid's settings.
  build.activation.patchLoginInnerForAndroidEnv = let
    # Script to inject into login-inner (written to a file for clean insertion)
    termuxEnvLoaderScript = pkgs.writeText "termux-env-loader.sh" ''
      # Source Android environment variables (restored from termux.env)
      # These are erased by the login script before proot runs
      # Filter out PATH, HOME, USER, TMPDIR, LANG, TERM which are managed by nix-on-droid
      if [ -f "${termuxEnvPath}" ]; then
        eval "$(${pkgs.gnugrep}/bin/grep -v -E '^export (PATH|HOME|USER|TMPDIR|LANG|TERM)=' "${termuxEnvPath}")"
      fi
    '';
    # Marker to detect if already patched
    marker = "# Source Android environment variables";
  in ''
    patch_login_inner() {
      local file="$1"
      if [ -f "$file" ] && ! ${pkgs.gnugrep}/bin/grep -q "${marker}" "$file"; then
        $VERBOSE_ECHO "Patching $file to source Android environment variables..."
        # Use awk to insert after "set -eo pipefail" line
        $DRY_RUN_CMD ${pkgs.gawk}/bin/awk '
          /^set -eo pipefail$/ {
            print
            while ((getline line < "${termuxEnvLoaderScript}") > 0) print line
            next
          }
          { print }
        ' "$file" > "$file.patched" && $DRY_RUN_CMD ${pkgs.coreutils}/bin/mv "$file.patched" "$file"
      fi
    }

    # Patch current login-inner
    patch_login_inner /usr/lib/login-inner
    # Patch staged login-inner (will become active on next login)
    patch_login_inner /usr/lib/.login-inner.new
  '';
}
