# Copyright (c) 2019-2022, see AUTHORS. Licensed under MIT License, see LICENSE.
# Modified for fakechroot with Android glibc support

{ config, writeScript, writeText }:

let
  inherit (config.build) installationDir;
  
  # Paths for fakechroot login
  androidGlibc = config.build.androidGlibc or null;
  androidFakechroot = config.build.androidFakechroot or null;
  packAuditLib = config.build.packAuditLib or null;
  standardGlibc = config.build.standardGlibc or null;
  bashInteractive = config.build.bashInteractive or null;
in

writeScript "login" ''
  #!/system/bin/sh
  # This file is generated by Nix-on-Droid with fakechroot support. DO NOT EDIT.
  set -eu

  export USER="${config.user.userName}"
  export HOME="${config.user.home}"

  # Debug hook: source user script if it exists (for debugging/overrides)
  # Create ~/.config/nix-on-droid/login-debug.sh to customize login behavior
  DEBUG_SCRIPT="${config.user.home}/.config/nix-on-droid/login-debug.sh"
  if [ -f "$DEBUG_SCRIPT" ]; then
    . "$DEBUG_SCRIPT"
  fi

  # Install pending login-inner if not in use
  if test -e ${installationDir}/usr/lib/.login-inner.new; then
    echo "Installing new login-inner..."
    /system/bin/mv ${installationDir}/usr/lib/.login-inner.new ${installationDir}/usr/lib/login-inner
  fi

  # Fakechroot configuration
  STORE="${installationDir}/nix/store"
  LD_LINUX="$STORE/${baseNameOf androidGlibc}/lib/ld-linux-aarch64.so.1"
  BASH_BIN="$STORE/${baseNameOf bashInteractive}/bin/bash"
  FAKECHROOT_LIB="$STORE/${baseNameOf androidFakechroot}/lib/fakechroot/libfakechroot.so"
  # pack-audit.so is in nix store, add installationDir prefix for outside-proot access
  AUDIT_LIB="${installationDir}${packAuditLib}"
  LOGIN_INNER="${installationDir}/usr/lib/login-inner"

  # Verify critical files exist
  for _file in "$LD_LINUX" "$BASH_BIN" "$FAKECHROOT_LIB" "$AUDIT_LIB" "$LOGIN_INNER"; do
    if [ ! -e "$_file" ]; then
      echo "Error: Required file not found: $_file" >&2
      exit 1
    fi
  done

  # Set up fakechroot environment
  export FAKECHROOT="true"
  export FAKECHROOT_BASE="${installationDir}"

  # ELF loader configuration - passed to ld.so for child processes
  export FAKECHROOT_ELFLOADER="$LD_LINUX"
  export FAKECHROOT_ELFLOADER_OPT_ARGV0="--argv0"
  export FAKECHROOT_ELFLOADER_OPT_AUDIT="$AUDIT_LIB"
  export FAKECHROOT_ELFLOADER_OPT_PRELOAD="$FAKECHROOT_LIB"

  # Paths to include in fakechroot translation (all others are passed through)
  # Only include paths that exist in ${installationDir} (the fakechroot base)
  # /home is outside fakechroot base, so $HOME is used directly without translation
  export FAKECHROOT_INCLUDE_PATH="/nix:/etc:/usr:/bin:/tmp:/root:/dev"

  # glibc redirection config for pack-audit.so
  export STANDARD_GLIBC="${baseNameOf standardGlibc}"
  export ANDROID_GLIBC="${baseNameOf androidGlibc}"

  # Execute using Android glibc's ld.so
  exec "$LD_LINUX" \
    --argv0 "$BASH_BIN" \
    --audit "$AUDIT_LIB" \
    --preload "$FAKECHROOT_LIB" \
    "$BASH_BIN" "$LOGIN_INNER" "$@"
''
